CT.require("CT.align");
CT.require("CT.data");
CT.require("CT.db");
CT.require("CT.dom");
CT.require("CT.key");
CT.require("CT.layout");
CT.require("CT.modal");
CT.require("CT.parse");
CT.require("CT.pubsub");
CT.require("CT.storage");
CT.require("CT.trans");
CT.require("core");
CT.require("CT.cc");
CT.require("user.core");
CT.require("zero.core");
CT.require("vu.core");
CT.require("vu.audio");
CT.require("vu.clix");
CT.require("vu.storage");
CT.require("vu.squad");
CT.require("vu.lang");
CT.require("vu.live");
CT.require("vu.multi");
CT.require("vu.portal");
CT.require("vu.controls");
CT.require("vu.help");
CT.require("vu.game");
CT.require("vu.menu.Map");
CT.require("vu.menu.Game");
CT.require("vu.builders.adventure");

CT.onload(function() {
	CT.initCore();
	vu.core.init();
	vu.storage.init(vu.builders.adventure.menus, true);
});